### ISSUE TITLE
Crashes when launched on  macOS Monterey [12.3]

### ISSUE THREAD

**Issue by vladdoster** [beeware/podium#56]
**Describe the bug**

Podium fails to run and logs indicate it is crashing.

**To Reproduce**

1. Install `Podium` via .DMG via gh-r
1. Run ./Applications/Podium.app/Contents/MacOS/Podium

**Expected behavior**

The Podium app to run and display the GUI.

**Screenshots**

```console
/Applications/Podium.app/Contents/MacOS
ᐳ ./Podium
Traceback (most recent call last):
  File "/Applications/Podium.app/Contents/Resources/Support/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Applications/Podium.app/Contents/Resources/Support/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Applications/Podium.app/Contents/Resources/app/podium/__main__.py", line 7, in <module>
    start()
  File "/Applications/Podium.app/Contents/Resources/app/podium/__main__.py", line 4, in start
    main().main_loop()
  File "/Applications/Podium.app/Contents/Resources/app/podium/app.py", line 127, in main
    return Podium()
  File "/Applications/Podium.app/Contents/Resources/app/podium/app.py", line 11, in __init__
    document_types={'podium': SlideDeck}
  File "/Applications/Podium.app/Contents/Resources/app_packages/toga/app.py", line 468, in __init__
    factory=factory,
  File "/Applications/Podium.app/Contents/Resources/app_packages/toga/app.py", line 176, in __init__
    self.factory = get_platform_factory(factory)
  File "/Applications/Podium.app/Contents/Resources/app_packages/toga/platform.py", line 36, in get_platform_factory
    from toga_cocoa import factory
  File "/Applications/Podium.app/Contents/Resources/app_packages/toga_cocoa/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/Applications/Podium.app/Contents/Resources/app_packages/toga_cocoa/app.py", line 13, in <module>
    from .keys import cocoa_key
  File "/Applications/Podium.app/Contents/Resources/app_packages/toga_cocoa/keys.py", line 3, in <module>
    from toga_cocoa.libs import (
  File "/Applications/Podium.app/Contents/Resources/app_packages/toga_cocoa/libs/__init__.py", line 1, in <module>
    from .appkit import *
  File "/Applications/Podium.app/Contents/Resources/app_packages/toga_cocoa/libs/appkit.py", line 24, in <module>
    NSAlert = ObjCClass('NSAlert')
  File "/Applications/Podium.app/Contents/Resources/app_packages/rubicon/objc/api.py", line 734, in __new__
    ptr, name = cls._new_from_name(name_or_ptr)
  File "/Applications/Podium.app/Contents/Resources/app_packages/rubicon/objc/api.py", line 642, in _new_from_name
    raise NameError("ObjC Class '%s' couldn't be found." % name)
NameError: ObjC Class 'b'NSAlert'' couldn't be found.
```

**Environment:**

 - Operating System:
 
 ```bash
 Darwin 21.4.0 
 Darwin Kernel Version 21.4.0
 root:xnu-8020.100.406.0.1~18/RELEASE_X86_64 
 x86_64
 ```

 - Python version:
 
 ```bash
 Python 3.9.10 (main, Jan 15 2022, 11:48:04)
 [Clang 13.0.0 (clang-1300.0.29.3)]
 ```

 - Software versions:
   - Briefcase: Unsure
   - Toga: Unsure 

**Additional context**

**Comment by emiola** [comment]
It happened also on macOS 12.4. Any solutions?
